services:
  - type: web
    name: telegram-video-streaming-linker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: 8246937087:AAFhqfSWsL8qKUI1zZsnGH02mc0Ji3aywe8
        sync: false
    runtime: python@3.11
